return {
  require "no-clown-fiesta.groups.git",
  require "no-clown-fiesta.groups.highlights",
  require "no-clown-fiesta.groups.lsp",
  require "no-clown-fiesta.groups.markdown",
  require "no-clown-fiesta.groups.mason",
  require "no-clown-fiesta.groups.neogit",
  require "no-clown-fiesta.groups.nvim-cmp",
  require "no-clown-fiesta.groups.nvim-tree",
  require "no-clown-fiesta.groups.statusline",
  require "no-clown-fiesta.groups.telescope",
  require "no-clown-fiesta.groups.treesitter",
  require "no-clown-fiesta.groups.whichkey",
  require "no-clown-fiesta.groups.neotest",
  require "no-clown-fiesta.groups.dapui",
}
